package initialize

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/alenicomar/oxy-backup/internal/config"
	"gopkg.in/yaml.v3"
)

const configFileName = "oxy.yaml"

// InitOptions holds the collected configuration for initializing a repository.
type InitOptions struct {
	Mode          string
	Container     string
	Host          string
	Port          int
	Username      string
	DbName        string
	DbDatabase    string
	PasswordEnv   string
	PartitionSize string
	OutputDir     string
	GitRemote     string
}

// BuildConfig constructs a config.Config from InitOptions.
func BuildConfig(opts *InitOptions) *config.Config {
	autoPush := true

	defaults := config.DatabaseConfig{
		Mode:          opts.Mode,
		Container:     opts.Container,
		Host:          opts.Host,
		Port:          opts.Port,
		Username:      opts.Username,
		Password:      fmt.Sprintf("${%s}", opts.PasswordEnv),
		PartitionSize: opts.PartitionSize,
		OutputDir:     opts.OutputDir,
	}

	db := config.DatabaseConfig{
		Name:     opts.DbName,
		Mode:     opts.Mode,
		Database: opts.DbDatabase,
	}

	return &config.Config{
		Version:  "1",
		Defaults: defaults,
		Git: config.GitConfig{
			AutoPush:              &autoPush,
			CommitMessageTemplate: "backup: {{.DbName}} @ {{.Timestamp}}",
			Remote:                "origin",
			Branch:                "main",
		},
		Logging: config.LoggingConfig{
			Level:  "info",
			Format: "text",
		},
		Databases: []config.DatabaseConfig{db},
	}
}

// WriteConfig marshals the config to YAML and writes it to targetDir/oxy.yaml.
func WriteConfig(targetDir string, cfg *config.Config) error {
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("marshaling config: %w", err)
	}

	header := []byte("# Oxy Backup configuration\n# Generated by: oxy init\n# See oxy.yaml.example for detailed documentation.\n\n")
	content := append(header, data...)

	path := filepath.Join(targetDir, configFileName)
	return os.WriteFile(path, content, 0644)
}
